# Generated by Django 6.0 on 2025-12-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
